### ISSUE TITLE
destination filename is missing first character

### ISSUE THREAD

**Issue by bkw** [izaakschroeder/vinyl-s3#1]
in my tests the first character of the destination file is dropped. I think filepath.substr in https://github.com/izaakschroeder/vinyl-s3/blob/master/lib/write-stream.js#L36 should not add +1 to the file.base.length.

**Comment by izaakschroeder** [comment]
For some definition of "soon". Pretty big refactor which I think both addresses this issue and makes the library easier to use. See updated README on homepage for new examples!
