### ISSUE TITLE
consider making options "gulp-data" compatible

### ISSUE THREAD

**Issue by jamestalmage** [izaakschroeder/vinyl-s3#21]
See https://www.npmjs.com/package/gulp-data .

```js
var data = require('gulp-data');
var s3 = require('vinyl-s3');
var gzip = require('gulp-gzip');

gulp.src('*.js')
  .pipe(gzip())
  .pipe(data({contentEncoding: 'gzip'})
  .pipe(s3.dest('s3:/mybucket'))
```

**Comment by izaakschroeder** [comment]
Is there a reason you want something like this instead of

```
.pipe(s3.dest('s3://mybucket?ContentEncoding=gzip'))
```

**Comment by izaakschroeder** [comment]
As a secondary note, `ContentEncoding` should be automatically detected for you as long as your files have two extensions. e.g. `.tar.gz`, `.html.gz`, `.css.gz`, etc.

**Comment by jamestalmage** [comment]
I am using it for an s3 hosted static website, and I would prefer the file names be `index.html` instead of `index.html.gz` (we are not supporting pre-gzip browsers since those went extinct almost 14 years ago).

I had oversimplified my example a bit.

```js
var data = require('gulp-data');
var s3 = require('vinyl-s3');
var gzip = require('gulp-gzip');
var merge = require('merge-stream');

merge(
  gulp.src('*.js')
    .pipe(gzip())
    .pipe(data({contentEncoding: 'gzip'}),

  gulp.src('*.png') //don't gzip binary data
)
  .pipe(s3.dest('s3:/mybucket'))

**Comment by izaakschroeder** [comment]
Looking at the documentation [here](https://github.com/jstuckey/gulp-gzip) the default behaviour for `gulp-gzip` is to append the extension; seems like you're making life more complex than it needs to be :smile: Just adjust the index document in S3 and you'll need neither any fancy configuration for `gulp-gzip` nor any for `vinyl-s3`.

If you really want to do things the hard way then you can definitely use the query parameter approach.

```javascript
var data = require('gulp-data');
var s3 = require('vinyl-s3');
var gzip = require('gulp-gzip');
var merge = require('merge-stream');

merge(
  gulp.src('*.js')
    .pipe(gzip({ append: false })) // you need to turn off append to remove the extension
  gulp.src('*.png') //don't gzip binary data
)
  .pipe(s3.dest('s3://mybucket?ContentEncoding=gzip'))
```

I'm hesitant to use `gulp-data` for configuration when I feel the existing approach works really well already. :smile:

**Comment by jamestalmage** [comment]
Fair enough.
I'm currently using the `setHeaders` option to accomplish what I want.
Your objections are well reasoned.
Closing
