### ISSUE TITLE
Upload Progress

### ISSUE THREAD

**Issue by cspicuzza** [izaakschroeder/vinyl-s3#33]
I understand this isn't really an "issue".  Is there a way to get vinyl-s3 to show the upload progress?

**Comment by toddpi314** [comment]
If it helps, the file definition is at https://github.com/izaakschroeder/vinyl-s3/blob/master/lib/vinyl-stream.js#L27-L36

You could write your own progress indicator with something that monitors the through pipe:

``` javascript
const countTotal = ...
let downloaded = 0;
...
.pipe(through2.obj((file, enc, callback) => {
      downloaded++;
      // TODO: Display progress
      callback();
}))
...
```
